app/notes/models.py
from app.extensions.database import db
from sqlalchemy.sql import func

class Note(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    data = db.Column(db.String(10000))
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    edited = db.Column(db.Boolean, default=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

app/users/models.py
from flask_login import UserMixin
from app.extensions.database import db


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))
    picture_url = db.Column(db.String(260))
    slug = db.Column(db.String(80), unique=True)
    notes = db.relationship('Note')

app/app.py
from flask import Flask
from app.extensions.database import db, migrate
from app.extensions.authentication import login_manager
from . import simple_pages, users, notes


def create_app():
  app = Flask(__name__)
  app.config.from_object('app.config')

  register_extensions(app)
  register_blueprints(app)

  return app

# Blueprints
def register_blueprints(app: Flask):
  app.register_blueprint(simple_pages.routes.blueprint)
  app.register_blueprint(users.routes.blueprint)
  app.register_blueprint(notes.routes.blueprint)

# Extensions
def register_extensions(app: Flask):
  db.init_app(app)
  migrate.init_app(app, db, compare_type=True)
  login_manager.init_app(app)
  

app/notes/__init__.py
from . import routes, models

app/notes/routes.py
import json
from flask import Blueprint, request, jsonify
from flask_login import current_user
from app.notes.models import Note
from app.extensions.database import db

blueprint = Blueprint('notes', __name__)

@blueprint.route('/delete-note', methods=['POST'])
def delete_note():  
    note = json.loads(request.data) # this function expects a JSON from the INDEX.js file 
    noteId = note['noteId']
    note = Note.query.get(noteId)
    if note:
        if note.user_id == current_user.id:
            db.session.delete(note)
            db.session.commit()

    return jsonify({})

@blueprint.route('/edit-note', methods=['POST'])
def edit_note():
    note = json.loads(request.data)
    note_id = note['noteId']
    note_data = note['noteData']
    edited_note = Note.query.filter_by(id=note_id, user_id=current_user.id).first()
    if not edited_note:
        flash('You do not have permission to edit this note', category='error')
    else:
        return jsonify({'noteData': edited_note.data})

app/simple_pages/__init__.py
from . import routes

app/simple_pages/routes.py
from flask import Blueprint, render_template, redirect, url_for, send_file, request, flash
from flask_login import login_user, login_required, current_user
from app.notes.models import Note
from app.users.models import User
from app.extensions.database import db

blueprint = Blueprint('simple_pages', __name__)

@blueprint.route('/')
def index():
  return render_template('simple_pages/index.html')

@blueprint.route('/dashboard', methods=['GET', 'POST'])
@login_required
def dashboard():
    if request.method == 'POST': 
        note_id = request.form.get('note_id')
        note_data = request.form.get('note')

        if note_id: # Editing an existing note
            note = Note.query.get(note_id)
            if note.user_id != current_user.id:
                flash('You do not have permission to edit this note', category='error')
            elif len(note_data) < 1:
                flash('Note is too short!', category='error') 
            else:
                note.data = note_data
                note.edited = True
                db.session.commit()
                flash('Note edited!', category='success')
        else: # Adding a new note
            if len(note_data) < 1:
                flash('Note is too short!', category='error') 
            else:
                new_note = Note(data=note_data, user_id=current_user.id)
                db.session.add(new_note)
                db.session.commit()
                flash('Note added!', category='success')

    notes = Note.query.filter_by(user_id=current_user.id).order_by(Note.date.desc()).all()
    return render_template('simple_pages/dashboard.html', notes=notes)

app/users/routes.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from app.users.models import User
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user, current_user
from app.extensions.database import db


blueprint = Blueprint('users', __name__)


@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('simple_pages.dashboard'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("users/login.html", user=current_user)


@blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('simple_pages.index'))


@blueprint.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists.', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(first_name) < 2:
            flash('First name must be greater than 1 character.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else:
            new_user = User(email=email, first_name=first_name, password=generate_password_hash(
                password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for("simple_pages.dashboard"))

    return render_template("users/register.html", user=current_user)

app/templates/00-base.html
<!DOCTYPE html>
<html class="html"lang="en-US">
  <head>
    {% block head %}
    <!-- specifying your document's character encoding-->
    <meta charset="utf-8" />

    <!-- author & description-->
    <meta name="author" content="EduardoNog" />
    <meta name="description" content="D.emo is a design tool powered by AI and allows you to create on-brand visual design effortlesly." />
    <meta name="viewport" content="width=device-width, initial-scale = 1"/>
   
    <!-- meta preview -->
    <meta property="og:image" content="https://developer.mozilla.org/static/img/opengraph-logo.png" />
    <meta property="og:description" content="D.emo is a design tool powered by AI and allows you to create on-brand visual design effortlesly." />
    <meta property="og:title" content="D.emo Visual Design Tool" />

    <!--favicon-->
    <link rel="icon" href="favicon.ico" type="image/x-icon" />
    
    <!--title-->
    <title>{% block title %}{% endblock %}</title>

    <!-- load font -->
    <link rel="preconnect" href="https://fonts.googleapis.com"> 
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> 
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans&display=swap" rel="stylesheet">

    
    <!--CSS-->
    
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='buttons.css') }}"/>
    <link rel="stylesheet" type="text/css" href= "{{ url_for('static', filename='theme-light.css') }}" />
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='tokens-colors.css') }}" />
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='tokens-typography.css') }}" />
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='containers.css') }}" />
    {% endblock %}

    <!--JavaScript-->
    <script src="{{ url_for('static', filename='index.js') }}"></script>

  </head>

  <body class ="body"> 

    <!--navbar-->
    <div class="navbar-wrap">
    <nav class="navbar">
      <div class="logo-wrap">
        <img id="menu-navbar" class="menu-navbar" src = "{{ url_for('static', filename='menu_24px.svg') }}" alt="menu"/>
        <a  href="/" class="nav-logo-link" alt="D.emo logo">d.emo</a>
      </div>
      <div class="nav-items">
        {% if current_user.is_authenticated %}
        <a href="/dashboard" class="nav-link">{{ current_user.first_name }}</a>
        <a href="/dashboard"class="avatar-icon"></a>
        {% else %}
        <a href="#" class="nav-link">Solution</a>
        <a href="#" class="nav-link">Pricing</a>
        <a href="#" class="nav-link">Contact</a>
        <a href="/sign-up" class="nav-link">Register</a>
        <a href="/login" class="button-primary">Login</a>
        {% endif %}    
      </div>
    </nav>
    <div id="nav-menu-open" class="nav-menu-open" id="nav-menu-open">
      <a href="#" class="nav-link">Menu item 1</a>
      <a href="#" class="nav-link">Menu item 1</a>
      <a href="#" class="nav-link">Menu item 1</a>
    </div> 
  </div>

    <!--pop up--> 
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
          {% if category == 'error' %}
            <div class="pop-up-error" role="alert">
              {{ message }}
              <button type="button" class="#danger" data-dismiss="alert">
                <span aria-hidden="true"> &times; </span>
              </button>
            </div>
          {% else %}
            <div class="pop-up-succs" role="alert">
              {{ message }}
              <button type="button" class="#sucess" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          {% endif %}
        {% endfor %}
      {% endif %}
    {% endwith %}

    <!--content will be added here--> 
    <main>
    {% block content %}
    
    {% endblock %}   
    </main>
    
    

    <footer class="footer-sign">
      {% if current_user.is_authenticated %}
      <a href="{{ url_for('users.logout') }}" class="label-medium" style="text-decoration: none; color:var(--md-ref-palette-neutral80)" >Logout</a>
      {% else %}
      <label class="label-medium">©2023 d.emo</label>
      {% endif %} 
      <label class="label-medium">All rights reserved</label>
      <label class="label-medium">Legal & Imprint</label>
    </footer>
    
  </body>
</html>

app/templates/main_pages/01-index.html
{% extends "00-base.html" %} 
{% block title %} Home {% endblock %} 
{% block content %}
  <!--Hero section-->
  <section class="section-full-h">
    <!--container 50%--> 
    <div class="container-medium-v">
      <h1 class="display-large">Brand consistency made easy</h1>
      <p class="title-large"> D.emo is a powerful tool for documenting and replicating visual communication.</p>
      <a href="/login" class="button-primary">Start using it!</a>
    </div>
  </section> 
{% endblock %}
  

app/templates/simple_pages/dashboard.html
{% extends "00-base.html" %} 
{% block title %} Poster Generator {% endblock %} 
{% block content%}
<section class="section-full-h" style="display:inline-flex">
  <div class="container-small-v">
    <h1 class="headline-medium">Content</h1>
    <h5 class="body-large">Add the information you want to showcase with your artwork </h5>
    <ul class="body-large" id="notes">
      {% for note in current_user.notes %}
        <li>
          {{ note.data }}
          <button type="button" onClick="editNote({{ note.id }}, '{{ note.data }}')">
            <span aria-hidden="true">&#9998;</span>
          </button>
          <button type="button" onClick="deleteNote({{ note.id }})">
            <span aria-hidden="true">&times;</span>
          </button>
        </li>
      {% endfor %}
    </ul>
    <form class="login-form" method="POST">
      <textarea class="label-large" name="note" id="note"></textarea>
      <br />
      <br />
      <input type="hidden" id="note-id" name="note-id" value="">
      <button class="button-primary" type="submit" id="add-note-button">Add Content</button>
      <button class="button-primary" type="button" id="update-note-button" style="display: none;">Update Content</button>
    </form>
  </div>
  <div class="container-small-v">

  </div>
</section>

{% block javascript %}
<script type="text/javascript">
  function editNote(noteId, noteData) {
    document.getElementById("note").value = noteData;
    document.getElementById("note-id").value = noteId;
    document.getElementById("add-note-button").style.display = "none";
    document.getElementById("update-note-button").style.display = "block";
  }

  function deleteNote(noteId) {
    fetch("/delete-note", {
      method: "POST",
      body: JSON.stringify({ noteId: noteId }),
    }).then((_res) => {
      window.location.href = "/dashboard";
    });
  }

  document.getElementById("update-note-button").addEventListener("click", function() {
    var noteId = document.getElementById("note-id").value;
    var noteData = document.getElementById("note").value;
    fetch("/update-note", {
      method: "POST",
      body: JSON.stringify({ noteId: noteId, noteData: noteData }),
    }).then((_res) => {
      window.location.href = "/dashboard";
    });
  });
</script>
  {% endblock %}            
{% endblock %}

app/templates/simple_pages/index.html
{% extends "00-base.html" %} 
{% block title %} Home {% endblock %} 
{% block content %}
  <!--Hero section-->
  <section class="section-full-h" background-image="url(https://github.com/eduarnog/demo/blob/main/app/static/hero.jpg?raw=true)">
    <!--container 50%--> 
    <div class="container-medium-v">
      <h1 class="display-large">On-brand visual communication made easy</h1>
      <p class="title-large"> D.emo is a powerful tool for documenting and generating visual communication effortlessly.</p>
      <a href="/login" class="button-primary">Start using it!</a>
    </div>
  </section> 
{% endblock %}
  

app/templates/users/02-log-in.html
{% extends "00-base.html" %} 
{% block title %} Login {% endblock %} 
{% block content%}
      <!--Hero section-->
      <section class="section-full-h">
        <!--container 30%--> 
        <div class="container-small-v">
          <h1 class="display-medium">Hello there</h1>
            {{% if user.is_authenticated %}}
            <h1> stranger </h1>
            {{% else %}}
            <h1> stranger </h1>
          <p class="body-large"> &#128110; Gotta check some id<br>
          Please add you log-in information.</p>

          <!--login form-->
          <form class="login-form" method="POST">
            <label class="label-large" for="email">Email</label>
            <input 
              id="email" 
              class ="input-primary-light",
              type="email" 
              name="email" 
              placeholder="Enter email"
              />
            <label class="label-large" for="password">Password</label>
            <input 
              class ="input-primary-light" 
              type="password"
              id="password"
              name="password"
              placeholder="Enter password"
            />
            <div class="group-wrap-16-v">
              <input class= "button-primary", type="submit"  value="Login">
              <a hefr="#" class="button-text">Forgot password?</a>
            </div>
          </form>

        </div>
      </section>        
{% endblock %}

app/templates/users/02-register.html
{% extends "00-base.html" %} 
{% block title %} Login {% endblock %} 
{% block content%}
    <section class="section-full-h">
    <div class="container-small-v">  
        <h1 class="display-medium">Signup</h1>
        <form class="login-form" method="POST">
            <div class="group-wrap-8-v">
                <label class="label-large" >First Name</label>
                <input
                    id="firstName" 
                    class="input-primary-light" 
                    name="firstName" 
                    placeholder="First Name"
                    type="text"
                />
            </div>
            <div class="group-wrap-8-v">
                <label class="label-large" >Email</label>
                <input
                    id="email" 
                    class="input-primary-light" 
                    name="email" 
                    placeholder="Email"
                    type="email"
                />
            </div>
            <div class="group-wrap-8-v">
                <label class="label-large" for="password1">Password</label>
                <input
                    id="password1"
                    name="password1" 
                    type="password" 
                    class="input-primary-light" 
                    placeholder="Choose a password"
                />
            </div>
            <div class="group-wrap-8-v">
                <label class="label-large" for="password2">Confirm Password</label>
                <input
                    id="password2"
                    name="password2"
                    type="password" 
                    class="input-primary-light"  
                    placeholder="Confirm password"
                />
            </div>
            <br/>
            <button type="submit" class="button-primary">Register</button>
        </form>
    </div>
    </section>
{% endblock %}

app/templates/users/03-dashboard.html
{% extends "00-base.html" %} 
{% block title %} Poster Generator {% endblock %} 
{% block content%}
<section class="section-full-h">
  <div class="container-small-v">  
      <h1 class="display-medium">Content</h1>
      <form class="login-form" method="POST">
          <div class="group-wrap-8-v">
              <label class="label-large">Title</label>
              <input
                  id="title" 
                  class="input-primary-light" 
                  name="title" 
                  placeholder="title"
                  type="text"
              />
          </div>
          <div class="group-wrap-8-v">
              <label class="label-large" >Description</label>
              <input
                  id="description" 
                  class="input-primary-light" 
                  name="description" 
                  placeholder="Description"
                  type="text"
              />
          </div>
          <br/>
          <button type="submit" class="button-primary">Generate</button>
      </form>
  </div>
  </section>              
      {% endblock %}

app/templates/users/04-new-print-01.html
                   
    <main>
      <!--Projects: this section allows user to start or continue a project--> 
      <section class="project-section">
        <div>
          <h1 class="display-medium">Lorem ispum</h1>
          <p></p>
          <div>
            <label class="container">One
              <input type="checkbox" checked="checked">
              <span class="checkmark"></span>
            </label>
            <label class="container">Two
              <input type="checkbox">
              <span class="checkmark"></span>
            </label>
            <label class="container">Three
              <input type="checkbox">
              <span class="checkmark"></span>
            </label>
            <label class="container">Four
              <input type="checkbox">
              <span class="checkmark"></span>
            </label>
          </div>  
        </div>
        
      </section>              
    </main>
    

app/templates/users/login.html
{% extends "00-base.html" %} 
{% block title %} Login {% endblock %} 
{% block content%}
      <!--Hero section-->
      <section class="section-full-h">
        <!--container 30%--> 
        <div class="container-small-v">
          <h1 class="display-medium">Hello there </br> stranger </h1>
          <p class="body-large"> &#128110; Gotta check some id<br>
          Please add you log-in information.</p>

          <!--login form-->
          <form class="login-form" method="POST">
            <label class="label-large" for="email">Email</label>
            <input 
              id="email" 
              class ="input-primary-light",
              type="email" 
              name="email" 
              placeholder="Enter email"
              />
            <label class="label-large" for="password">Password</label>
            <input 
              class ="input-primary-light" 
              type="password"
              id="password"
              name="password"
              placeholder="Enter password"
            />
            <div class="group-wrap-16-v">
              <input class= "button-primary", type="submit"  value="Login">
              <a hefr="#" class="button-text">Forgot password?</a>
            </div>
          </form>

        </div>
      </section>        
{% endblock %}

app/templates/users/new_print.html
                   
    <main>
      <!--Projects: this section allows user to start or continue a project--> 
      <section class="project-section">
        <div>
          <h1 class="display-medium">Lorem ispum</h1>
          <p></p>
          <div>
            <label class="container">One
              <input type="checkbox" checked="checked">
              <span class="checkmark"></span>
            </label>
            <label class="container">Two
              <input type="checkbox">
              <span class="checkmark"></span>
            </label>
            <label class="container">Three
              <input type="checkbox">
              <span class="checkmark"></span>
            </label>
            <label class="container">Four
              <input type="checkbox">
              <span class="checkmark"></span>
            </label>
          </div>  
        </div>
        
      </section>              
    </main>
    

app/templates/users/register.html
{% extends "00-base.html" %} 
{% block title %} Login {% endblock %} 
{% block content%}
    <section class="section-full-h">
    <div class="container-small-v">  
        <h1 class="display-medium">Signup</h1>
        <form class="login-form" method="POST">
            <div class="group-wrap-8-v">
                <label class="label-large" >First Name</label>
                <input
                    id="firstName" 
                    class="input-primary-light" 
                    name="firstName" 
                    placeholder="First Name"
                    type="text"
                />
            </div>
            <div class="group-wrap-8-v">
                <label class="label-large" >Email</label>
                <input
                    id="email" 
                    class="input-primary-light" 
                    name="email" 
                    placeholder="Email"
                    type="email"
                />
            </div>
            <div class="group-wrap-8-v">
                <label class="label-large" for="password1">Password</label>
                <input
                    id="password1"
                    name="password1" 
                    type="password" 
                    class="input-primary-light" 
                    placeholder="Choose a password"
                />
            </div>
            <div class="group-wrap-8-v">
                <label x for="password2">Confirm Password</label>
                <input
                    id="password2"
                    name="password2"
                    type="password" 
                    class="input-primary-light"  
                    placeholder="Confirm password"
                />
            </div>
            <br/>
            <button type="submit" class="button-primary">Register</button>
        </form>
    </div>
    </section>
{% endblock %}